apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zvx21kg80-go
  janus-idp.io/tekton: zvx21kg80-go
  backstage.io/kubernetes-id: zvx21kg80-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zvx21kg80-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
